server:
  port: 8081


#多数据源
spring:
  application:
    name: oa-notice
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      keep-alive: true
    dynamic:
      primary: mysql
      datasource:
        mysql:
          username: root
          password: daas2020
          url: jdbc:mysql://172.28.7.100:3306/fill_in?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          driver-class-name: com.mysql.cj.jdbc.Driver
        impala:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:impala://172.28.9.101:21051/bigdata;AuthMech=0;
          driver-class-name: com.cloudera.impala.jdbc41.Driver






# mybatis 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

## -------------------------------------------------

oa:
  senderCoder: 99999990
  templateCode: DSJTBFK